[package]
name = "handwriter-core"
description = "HandWriter core: handwriting and drawings to pencil gcode"
version.workspace = true
edition.workspace = true

[dependencies]
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
